import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';
import { v4 as uuidv4 } from 'npm:uuid@9.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json();
    const { 
      serviceRequestId, 
      supplierOwnBookingId,
      notificationType = 'both',
      autoGenerated = false,
      additionalPhone,
      skipPassengerNotification = false
    } = body;

    const idToSearch = serviceRequestId || supplierOwnBookingId;

    if (!idToSearch) {
      return Response.json({ success: false, error: 'ID da viagem é obrigatório' }, { status: 400 });
    }

    let trip = null;
    let tripType = null;

    // 1. Try ServiceRequest first
    const serviceRequests = await base44.asServiceRole.entities.ServiceRequest.filter({ id: idToSearch });
    if (serviceRequests.length > 0) {
      trip = serviceRequests[0];
      tripType = 'service_request';
    } else {
      // 2. Fallback to SupplierOwnBooking
      const ownBookings = await base44.asServiceRole.entities.SupplierOwnBooking.filter({ id: idToSearch });
      if (ownBookings.length > 0) {
        trip = ownBookings[0];
        tripType = 'supplier_own_booking';
      }
    }

    if (!trip) {
      return Response.json({ success: false, error: 'Viagem não encontrada (ServiceRequest ou SupplierOwnBooking)' }, { status: 404 });
    }

    // Find or create the shared timeline record
    const filterQuery = { status: 'active' };
    if (tripType === 'service_request') {
      filterQuery.service_request_id = trip.id;
    } else {
      filterQuery.supplier_own_booking_id = trip.id;
    }

    const existingTimelines = await base44.asServiceRole.entities.SharedTripTimeline.filter(filterQuery);
    let sharedTimeline;
    let isNewLink = false;

    if (existingTimelines.length > 0) {
      sharedTimeline = existingTimelines[0];
    } else {
      isNewLink = true;
      const token = uuidv4();
      let currentUser = null;
      try { currentUser = await base44.auth.me(); } catch (e) {}

      const createPayload = {
        token,
        shared_by_user_id: currentUser?.id || null,
        first_shared_at: new Date().toISOString(),
        status: 'active',
        auto_generated: autoGenerated,
        shared_to_contacts: []
      };
      if (tripType === 'service_request') {
        createPayload.service_request_id = trip.id;
      } else {
        createPayload.supplier_own_booking_id = trip.id;
      }
      sharedTimeline = await base44.asServiceRole.entities.SharedTripTimeline.create(createPayload);
    }

    // Build timeline URL
    const baseUrl = Deno.env.get('BASE_URL') || `https://${req.headers.get('host')}`;
    const timelineUrl = `${baseUrl}/SharedTripTimeline?token=${sharedTimeline.token}`;
    console.log('[generateSharedTimelineLink] URL gerada:', timelineUrl);

    // If trip is already in an advanced state, skip "a_caminho" notification
    const currentStatus = trip.driver_trip_status || trip.driver_current_status;
    const advancedStatuses = ['passageiro_embarcou', 'a_caminho_destino', 'chegou_destino', 'finalizada', 'cancelada_motorista', 'no_show'];
    if (advancedStatuses.includes(currentStatus)) {
      console.log(`[generateSharedTimelineLink] Status avançado (${currentStatus}), pulando notificação "A Caminho".`);
      return Response.json({
        success: true,
        timelineUrl,
        message: 'Link obtido, notificação ignorada pois a viagem já está em andamento/finalizada.'
      });
    }

    // Normalize contact data (ServiceRequest vs SupplierOwnBooking field names)
    const passengerName = trip.passenger_name || trip.customer_name || '';
    const passengerEmail = skipPassengerNotification ? null : (trip.passenger_email || trip.customer_email || null);
    const passengerPhone = skipPassengerNotification ? null : (trip.passenger_phone || trip.customer_phone || null);
    const tripNumber = trip.request_number || trip.booking_number;

    // Build normalized trip for the centralized notification system
    const notificationTrip = {
      ...trip,
      passenger_name: passengerName,
      passenger_email: passengerEmail,
      passenger_phone: passengerPhone,
      request_number: tripNumber,
      notification_phones: [
        ...(Array.isArray(trip.notification_phones) ? trip.notification_phones : []),
        ...(additionalPhone ? [additionalPhone] : [])
      ]
    };

    // Delegate to centralized notification system (uses NotificationTemplate from DB with fallback)
    let emailSent = false;
    let whatsappSent = false;
    let emailError = null;
    let whatsappError = null;

    try {
      const res = await base44.asServiceRole.functions.invoke('sendTripStatusNotification', {
        trip: notificationTrip,
        newStatus: 'a_caminho',
        timelineUrl
      });
      const results = (res && res.results) ? res.results : [];
      emailSent = results.some(r => r.type === 'email' && r.status === 'sent');
      whatsappSent = results.some(r => r.type === 'whatsapp' && r.status === 'sent');
    } catch (error) {
      console.error('[generateSharedTimelineLink] Erro ao enviar notificação:', error);
      emailError = error.message;
      whatsappError = error.message;
    }

    // Record notified contacts on the timeline record
    const sentContacts = [];
    if (passengerEmail && emailSent) {
      sentContacts.push({ contact_type: 'email', contact_value: passengerEmail, sent_at: new Date().toISOString() });
    }
    if (passengerPhone && whatsappSent) {
      sentContacts.push({ contact_type: 'phone', contact_value: passengerPhone, sent_at: new Date().toISOString() });
    }
    if (additionalPhone && whatsappSent) {
      sentContacts.push({ contact_type: 'phone', contact_value: additionalPhone, sent_at: new Date().toISOString() });
    }

    if (sentContacts.length > 0) {
      await base44.asServiceRole.entities.SharedTripTimeline.update(sharedTimeline.id, {
        shared_to_contacts: [
          ...(sharedTimeline.shared_to_contacts || []),
          ...sentContacts
        ]
      });
    }

    return Response.json({
      success: true,
      timelineUrl,
      isNewLink,
      emailSent,
      whatsappSent,
      emailError,
      whatsappError,
      message: isNewLink 
        ? 'Link de linha do tempo criado e enviado com sucesso!'
        : 'Link existente reenviado com sucesso!'
    });

  } catch (error) {
    console.error('[generateSharedTimelineLink] Erro:', error);
    return Response.json({
      success: false,
      error: error.message || 'Erro ao gerar link da linha do tempo'
    }, { status: 500 });
  }
});